#ifndef STYLES_H
#define STYLES_H

#include <windows.h>

#define COLOR_BG_DARK RGB(18, 16, 18)
#define COLOR_BG_SIDEBAR RGB(24, 20, 22)
#define COLOR_BG_BLUE RGB(50, 30, 35)
#define COLOR_BG_BLUE_HOVER RGB(65, 40, 45)
#define COLOR_TEXT_WHITE RGB(245, 245, 250)
#define COLOR_TEXT_GRAY RGB(170, 160, 165)
#define COLOR_TEXT_LIGHT_GRAY RGB(200, 190, 195)
#define COLOR_ACCENT_BLUE RGB(180, 70, 80)
#define COLOR_ACCENT_BLUE_DARK RGB(150, 55, 65)
#define COLOR_ACCENT_BLUE_LIGHT RGB(200, 85, 95)
#define COLOR_MESSAGE_OTHER RGB(35, 28, 32)
#define COLOR_MESSAGE_USER RGB(140, 60, 70)
#define COLOR_INPUT_BG RGB(30, 26, 28)
#define COLOR_INPUT_BORDER RGB(60, 45, 50)
#define COLOR_BUTTON_HOVER RGB(200, 90, 100)

#define FONT_FAMILY "Segoe UI"
#define FONT_SIZE_LARGE 24
#define FONT_SIZE_MEDIUM 16
#define FONT_SIZE_NORMAL 14
#define FONT_SIZE_SMALL 12
#define FONT_WEIGHT_NORMAL FW_NORMAL
#define FONT_WEIGHT_SEMIBOLD FW_SEMIBOLD
#define FONT_WEIGHT_BOLD FW_BOLD

HFONT CreateAppFont(int size, int weight = FONT_WEIGHT_NORMAL);
HFONT CreateInputFont(int size, int weight = FONT_WEIGHT_NORMAL);
void DrawRoundedRect(HDC hdc, RECT r, COLORREF color, int radius);

#endif

